language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: yuQ330R3g+1XPYqLRUSaeWFz0CkohxiNJFA8q0OmiOVchmlA3j03zOlcD7Z4LEBhU3wQMNW2tUnZxDRq+pS3hTAymAbreWmedYG3iOQbfI3w1zlUCCDvbV8Su76976Zxy28A0eDhhe1grEb85rWDPonnm4d2Qj6Pe+Ey7pTFx1N7zukazE+WqgsDN4bfts1zJHCBv7VTBXuwVOIgbbeBYzOVFXSgu/22axolPgxdlcoBcyisW4iNY8OcJJ2mkHIZjuWN+8utCxQ9SiF77n7MNuJvn7L27VgTIUDMEx0tolfe3Cv7aUP9vglOyxBXrRpHvnJzY8jHxodd/dB4I6S6I7YwPq/sm98ctxpeyvTMI97lJb6tvHn5K5DPb6U9HgThRv11rEwk2YfmxdC6/h7eZxWuMmbUjn1kOjG9Gw1UNPMNmK4IQIG4BoVxeDX71Z3PfK8rzF33BrnBO4z6NGLYIf3MdDMaN2It6Pbk6eEPaFHZNav5d4F+orUk1hmdfFaxPju1ov2FqNfJtJIfd7UVxvZkf1hiuUhHw2jzgEpUfvmeIuhXAyTr+efvchILZz88DJBMRsfZ0E9Unclzmwico9QyU/iWog0YmITyvMWE/v07/cu8tZ7bbCYU7IC1GpeNnJsNZS+BQZhJD0lpVEmQjDnjpQP0Yq7SK1O6FH5WJw0=
  app: blog-app-mongoose-challenge-solution
  on:
    repo: bryanspearman/blog-app-mongoose-challenge-solution
